import type { IcSectionId } from "./sections";

export interface BulletDef {
  metric_key: string;
  section: IcSectionId;
  label: string;
  description: string;
  unit: string;
  drill_id: string;
  higher_is_better: boolean;
  isMemberScale?: boolean;
}

export const BULLET_DEFS: BulletDef[] = [
  {
    metric_key: "tasks_completed",
    section: "task_delivery",
    label: "Tasks closed per developer",
    description: "Closed tasks divided by developer count over the period.",
    unit: "tasks",
    drill_id: "team-tasks",
    higher_is_better: true,
  },
  {
    metric_key: "task_dev_time",
    section: "task_delivery",
    label: "Task development time",
    description:
      "Per-task median time spent in development-in-progress statuses. Lower is better.",
    unit: "h",
    drill_id: "team-dev-time",
    higher_is_better: false,
  },
  {
    metric_key: "task_reopen_rate",
    section: "task_delivery",
    label: "Task reopen rate",
    description:
      "Share of closed tasks reopened later. Lower means fewer regressions.",
    unit: "%",
    drill_id: "team-reopen",
    higher_is_better: false,
  },
  {
    metric_key: "due_date_compliance",
    section: "task_delivery",
    label: "Due date compliance",
    description: "Share of tasks closed on or before their due date.",
    unit: "%",
    drill_id: "",
    higher_is_better: true,
  },
  {
    metric_key: "estimation_accuracy",
    section: "task_delivery",
    label: "Estimation accuracy",
    description:
      "How close estimates come to actual elapsed development time.",
    unit: "%",
    drill_id: "",
    higher_is_better: true,
  },
  {
    metric_key: "bugs_to_task_ratio",
    section: "task_delivery",
    label: "Bug share of closed tasks",
    description:
      "Bugs as a share of all closed tasks. Lower is better.",
    unit: "%",
    drill_id: "",
    higher_is_better: false,
  },
  {
    metric_key: "mean_time_to_resolution",
    section: "task_delivery",
    label: "Mean time to resolution",
    description: "Median lifetime of a closed issue, from create to close.",
    unit: "d",
    drill_id: "",
    higher_is_better: false,
  },
  {
    metric_key: "flow_efficiency",
    section: "task_delivery",
    label: "Flow efficiency",
    description:
      "Development-in-progress time divided by total lifetime. Higher = less waiting.",
    unit: "%",
    drill_id: "",
    higher_is_better: true,
  },
  {
    metric_key: "pickup_time",
    section: "task_delivery",
    label: "Pickup time",
    description: "Days from task created to first development status.",
    unit: "d",
    drill_id: "",
    higher_is_better: false,
  },

  {
    metric_key: "commits",
    section: "git_output",
    label: "Commits authored",
    description: "Distinct commits authored in the period.",
    unit: "count",
    drill_id: "commits",
    higher_is_better: true,
  },
  {
    metric_key: "prs_created",
    section: "git_output",
    label: "Pull requests created",
    description: "Pull requests authored in the period.",
    unit: "count",
    drill_id: "pull-requests",
    higher_is_better: true,
  },
  {
    metric_key: "prs_merged",
    section: "git_output",
    label: "Pull requests merged",
    description: "Authored pull requests that ended up merged.",
    unit: "count",
    drill_id: "",
    higher_is_better: true,
  },
  {
    metric_key: "clean_loc",
    section: "git_output",
    label: "Clean LOC",
    description:
      "Lines added excluding spec, config, and generated files. Signal of substantive code.",
    unit: "count",
    drill_id: "",
    higher_is_better: true,
  },
  {
    metric_key: "pr_cycle_time_h",
    section: "git_output",
    label: "PR cycle time",
    description:
      "Average hours from pull request opened to merged. Lower is better.",
    unit: "h",
    drill_id: "pull-requests",
    higher_is_better: false,
  },
  {
    metric_key: "pr_size",
    section: "git_output",
    label: "PR size",
    description:
      "Median lines changed per pull request. Smaller pull requests review faster.",
    unit: "count",
    drill_id: "",
    higher_is_better: false,
  },
  {
    metric_key: "merge_rate",
    section: "git_output",
    label: "PR merge rate",
    description:
      "Pull requests merged divided by created. Closer to 100% = less wasted review.",
    unit: "%",
    drill_id: "",
    higher_is_better: true,
  },
  {
    metric_key: "lines_per_commit",
    section: "git_output",
    label: "Lines per commit",
    description:
      "Average commit size. Smaller commits review better.",
    unit: "count",
    drill_id: "",
    higher_is_better: false,
  },
  {
    metric_key: "commits_per_active_day",
    section: "git_output",
    label: "Commits per active day",
    description: "Cadence on days with at least one commit.",
    unit: "count",
    drill_id: "",
    higher_is_better: true,
  },

  {
    metric_key: "prs_per_dev",
    section: "code_quality",
    label: "PRs merged per developer",
    description: "Merged pull requests divided by developer count.",
    unit: "",
    drill_id: "team-prs",
    higher_is_better: true,
  },
  {
    metric_key: "build_success",
    section: "code_quality",
    label: "Build success rate",
    description: "CI runs that finished green divided by total runs.",
    unit: "%",
    drill_id: "team-build",
    higher_is_better: true,
  },
  {
    metric_key: "pr_cycle_time",
    section: "code_quality",
    label: "Pull request cycle time",
    description: "Hours from pull request opened to merged.",
    unit: "h",
    drill_id: "team-pr-cycle",
    higher_is_better: false,
  },
  {
    metric_key: "bugs_fixed",
    section: "code_quality",
    label: "Bugs fixed",
    description: "Bug-type issues closed in the period.",
    unit: "count",
    drill_id: "team-bugs",
    higher_is_better: true,
  },

  {
    metric_key: "active_ai_members",
    section: "ai_adoption",
    label: "Active AI members",
    description: "Members with any AI tool activity in the period.",
    unit: "",
    drill_id: "",
    higher_is_better: true,
    isMemberScale: true,
  },
  {
    metric_key: "cursor_active",
    section: "ai_adoption",
    label: "Cursor — active members",
    description: "Members with Cursor activity in the period.",
    unit: "",
    drill_id: "",
    higher_is_better: true,
    isMemberScale: true,
  },
  {
    metric_key: "cc_active",
    section: "ai_adoption",
    label: "Claude Code — active members",
    description: "Members with Claude Code activity in the period.",
    unit: "",
    drill_id: "",
    higher_is_better: true,
    isMemberScale: true,
  },
  {
    metric_key: "team_ai_loc",
    section: "ai_adoption",
    label: "Team AI accepted lines",
    description: "Total lines accepted across all AI tools.",
    unit: "lines",
    drill_id: "",
    higher_is_better: true,
  },
  {
    metric_key: "cursor_acceptance",
    section: "ai_adoption",
    label: "Cursor acceptance rate",
    description: "Cursor suggestions accepted divided by suggestions shown.",
    unit: "%",
    drill_id: "",
    higher_is_better: true,
  },
  {
    metric_key: "cc_tool_acceptance",
    section: "ai_adoption",
    label: "Claude Code tool acceptance",
    description: "Claude Code tool calls accepted divided by proposed.",
    unit: "%",
    drill_id: "",
    higher_is_better: true,
  },
  {
    metric_key: "cursor_lines",
    section: "ai_adoption",
    label: "Cursor accepted lines",
    description: "Lines accepted from Cursor.",
    unit: "lines",
    drill_id: "",
    higher_is_better: true,
  },
  {
    metric_key: "cc_lines",
    section: "ai_adoption",
    label: "Claude Code accepted lines",
    description: "Lines accepted from Claude Code.",
    unit: "lines",
    drill_id: "",
    higher_is_better: true,
  },
  {
    metric_key: "ai_loc_share2",
    section: "ai_adoption",
    label: "AI code acceptance",
    description: "AI-assisted lines divided by clean LOC.",
    unit: "%",
    drill_id: "",
    higher_is_better: true,
  },

  {
    metric_key: "slack_messages_sent",
    section: "collaboration",
    label: "Messages sent",
    description: "Chat messages authored in the period.",
    unit: "messages",
    drill_id: "",
    higher_is_better: true,
  },
  {
    metric_key: "slack_active_days",
    section: "collaboration",
    label: "Active days",
    description: "Days with at least one chat message.",
    unit: "days",
    drill_id: "",
    higher_is_better: true,
  },
  {
    metric_key: "slack_dm_ratio",
    section: "collaboration",
    label: "DM ratio",
    description:
      "Share of chat messages that are direct messages. Higher = more 1:1 churn.",
    unit: "%",
    drill_id: "",
    higher_is_better: false,
  },
  {
    metric_key: "m365_emails_sent",
    section: "collaboration",
    label: "Emails sent",
    description: "Emails sent in the period.",
    unit: "emails",
    drill_id: "",
    higher_is_better: true,
  },
  {
    metric_key: "m365_emails_received",
    section: "collaboration",
    label: "Emails received",
    description: "Inbox email volume.",
    unit: "emails",
    drill_id: "",
    higher_is_better: true,
  },
  {
    metric_key: "m365_teams_chats",
    section: "collaboration",
    label: "Teams chats",
    description: "Direct messages and group chats sent.",
    unit: "messages",
    drill_id: "",
    higher_is_better: true,
  },
  {
    metric_key: "meeting_hours",
    section: "collaboration",
    label: "Meeting hours",
    description: "Hours in scheduled meetings. Lower is usually better.",
    unit: "h",
    drill_id: "",
    higher_is_better: false,
  },
  {
    metric_key: "meetings_count",
    section: "collaboration",
    label: "Meetings attended",
    description: "Distinct meetings attended.",
    unit: "meetings",
    drill_id: "",
    higher_is_better: true,
  },
  {
    metric_key: "meeting_free",
    section: "collaboration",
    label: "Meeting-free days",
    description: "Working days with no meetings.",
    unit: "days",
    drill_id: "",
    higher_is_better: true,
  },
];

export const BULLET_DEFS_BY_KEY: Record<string, BulletDef> = Object.fromEntries(
  BULLET_DEFS.map((d) => [d.metric_key, d]),
);

export function bulletDefsForSection(section: IcSectionId): BulletDef[] {
  return BULLET_DEFS.filter((d) => d.section === section);
}
