/**
 * HAI3 Application Component
 *
 * Renders the Layout with AppRouter for screen navigation.
 * Layout components are generated by `hai3 scaffold layout` and owned by the project.
 *
 * HAI3Provider (in main.tsx) handles:
 * - Redux Provider setup
 * - HAI3 context (app instance)
 *
 * Layout handles:
 * - Header, Menu, Footer, Sidebar rendering
 * - Theme-aware styling via hooks
 *
 * AppRouter handles:
 * - Screen lazy loading
 * - Navigation state
 *
 * StudioOverlay (dev mode only):
 * - Development tools for theme/screenset switching
 * - Language selection
 * - API mode toggle (services register their own mocks)
 *
 * Auth:
 * - OIDC bootstrap runs in main.tsx BEFORE React renders
 * - By the time App mounts, user is already authenticated
 * - AuthPlugin handles token injection and 401 → re-auth
 */

import { useEffect } from 'react';
import { AppRouter, useNavigation } from '@hai3/react';
import { Layout } from '@/app/layout';
import {
  INSIGHT_SCREENSET_ID,
  EXECUTIVE_VIEW_SCREEN_ID,
  MY_DASHBOARD_SCREEN_ID,
} from '@/screensets/insight/ids';

function App() {
  // Org overview (executive-view) hidden in prod until data quality lands —
  // issue #359. Catches deep links / bookmarks / history that resolve to
  // the screen and bounces them to the personal dashboard. Dev mode keeps
  // direct URL access so the screen stays demoable while disabled.
  const { currentScreen, currentScreenset, navigateToScreen } = useNavigation();
  useEffect(() => {
    if (import.meta.env.DEV) return;
    if (
      currentScreenset === INSIGHT_SCREENSET_ID &&
      currentScreen === EXECUTIVE_VIEW_SCREEN_ID
    ) {
      navigateToScreen(INSIGHT_SCREENSET_ID, MY_DASHBOARD_SCREEN_ID);
    }
  }, [currentScreen, currentScreenset, navigateToScreen]);

  return (
    <>
      <Layout>
        <AppRouter />
      </Layout>
    </>
  );
}

export default App;
