/**
 * Header Component
 *
 * Application header with user info display.
 * Generated by `hai3 scaffold layout`.
 */

import React, { useState } from 'react';
import { useAppSelector, type HeaderState } from '@hai3/react';
import { UserInfo } from '@hai3/uikit';
import { Icon } from '@iconify/react';
import { fetchCurrentUser } from '@/app/actions/bootstrapActions';

export interface HeaderProps {
  children?: React.ReactNode;
}

/**
 * Lock the refresh button for a short window after a click so rapid
 * re-clicks don't fire concurrent identity lookups with out-of-order
 * UserChanged emissions (last-write-wins on the slice).
 */
const REFRESH_LOCK_MS = 1500;

export const Header: React.FC<HeaderProps> = ({ children }) => {
  const headerState = useAppSelector((state) => state['layout/header'] as HeaderState | undefined);
  const [refreshing, setRefreshing] = useState(false);

  const user = headerState?.user;
  const loading = headerState?.loading ?? false;

  const handleRefresh = (): void => {
    if (refreshing) return;
    setRefreshing(true);
    fetchCurrentUser();
    window.setTimeout(() => setRefreshing(false), REFRESH_LOCK_MS);
  };

  return (
    <header className="h-16 flex items-center px-4 border-b border-border bg-background">
      {children}
      <div className="ml-auto flex items-center gap-2">
        <button
          type="button"
          aria-label="Refresh user and menu"
          title="Refresh user and menu"
          onClick={handleRefresh}
          disabled={refreshing}
          className="rounded-md p-1.5 text-gray-500 hover:bg-gray-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-600 disabled:opacity-50 disabled:cursor-not-allowed"
        >
          <Icon
            icon="lucide:refresh-cw"
            className={`w-4 h-4 ${refreshing ? 'animate-spin' : ''}`}
          />
        </button>
        <UserInfo
          displayName={user?.displayName}
          email={user?.email}
          avatarUrl={user?.avatarUrl}
          loading={loading}
        />
      </div>
    </header>
  );
};

Header.displayName = 'Header';
