/**
 * Layout Component
 *
 * Main layout orchestrator for the application.
 * This component is generated by `hai3 scaffold layout`.
 * Uses @hai3/uikit for UI components.
 */

import React, { useEffect, useState } from 'react';
import { Sheet, SheetContent } from '@hai3/uikit';
import { useAppSelector } from '@hai3/react';
import { Icon } from '@iconify/react';
import { fetchCurrentUser } from '@/app/actions/bootstrapActions';
import { initAuth } from '@/app/actions/authActions';
import { OidcManager } from '@/app/auth/OidcManager';
import { selectAuthStatus } from '@/app/slices/authSlice';
import { AuthErrorCard } from '@/screensets/auth/uikit/base/AuthErrorCard';
import { Footer } from './Footer';
import { Menu } from './Menu';
import { Sidebar } from './Sidebar';
import { Screen } from './Screen';
import { Popup } from './Popup';
import { Overlay } from './Overlay';
import { RoleSwitcher } from '@/screensets/insight/components/RoleSwitcher';
import { HAI3LogoIcon } from '@/app/icons/HAI3LogoIcon';
import { HAI3LogoTextIcon } from '@/app/icons/HAI3LogoTextIcon';

export interface LayoutProps {
  children?: React.ReactNode;
}

const RoleSwitcherSlot = (
  <div className="mt-auto border-t border-white/10 pt-1 pb-2">
    <RoleSwitcher />
  </div>
);

const MobileRoleSwitcherSlot = (
  <div className="mt-auto border-t border-white/10 pt-1 pb-2">
    <RoleSwitcher />
  </div>
);

export const Layout: React.FC<LayoutProps> = ({ children }) => {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);

  const authStatus = useAppSelector(selectAuthStatus);

  useEffect(() => {
    initAuth();
  }, []);

  // Fetch identity only after auth token is in the store
  useEffect(() => {
    if (authStatus === 'authenticated') {
      fetchCurrentUser();
    }
  }, [authStatus]);

  // Close mobile menu when viewport grows past mobile breakpoint
  useEffect(() => {
    const handler = () => {
      if (window.innerWidth >= 768) setMobileMenuOpen(false);
    };
    window.addEventListener('resize', handler);
    return () => window.removeEventListener('resize', handler);
  }, []);

  // Top-level guard: a terminal "unauthorized" state means the SPA already
  // tried a silent renew and the backend STILL rejected the token. Render
  // the error card instead of any app content; "sign in again" kicks off
  // a full redirect to the IdP. (Distinct from `expired`, which is a
  // mid-callback state handled in CallbackScreen.)
  if (authStatus === 'unauthorized') {
    return (
      <AuthErrorCard
        onRetry={() => {
          sessionStorage.clear();
          localStorage.clear();
          void OidcManager.signIn();
        }}
      />
    );
  }

  return (
    <div className="flex flex-col h-full w-full overflow-hidden">
      {/* Mobile top bar — visible only below md */}
      <div className="md:hidden flex items-center gap-3 px-4 h-12 bg-sidebar border-b border-sidebar-border flex-shrink-0">
        <button
          type="button"
          aria-label="Open navigation"
          onClick={() => setMobileMenuOpen(true)}
          className="text-sidebar-foreground/60 hover:text-sidebar-foreground transition-colors p-1 -ml-1"
        >
          <Icon icon="lucide:menu" className="w-5 h-5" />
        </button>
        <HAI3LogoIcon className="w-6 h-6 text-sidebar-foreground" />
        <HAI3LogoTextIcon className="h-4 text-sidebar-foreground" />
      </div>

      {/* Mobile nav sheet */}
      <Sheet open={mobileMenuOpen} onOpenChange={setMobileMenuOpen}>
        <SheetContent side="left" className="p-0 w-64 flex flex-col bg-sidebar border-r border-sidebar-border [&>button]:text-sidebar-foreground/40 [&>button]:hover:text-sidebar-foreground">
          <Menu onNavigate={() => setMobileMenuOpen(false)}>
            {MobileRoleSwitcherSlot}
          </Menu>
        </SheetContent>
      </Sheet>

      {/* Desktop row: Menu + Content */}
      <div className="flex flex-1 overflow-hidden">
        {/* Left nav — hidden on mobile, shown on md+ */}
        <div className="hidden md:flex md:h-full">
          <Menu>
            {RoleSwitcherSlot}
          </Menu>
        </div>

        {/* Right side: Content */}
        <div className="flex flex-col flex-1 overflow-hidden">
          {/* Main content area */}
          <div className="flex flex-1 overflow-hidden">
            {/* Main content */}
            <Screen>{children}</Screen>

            {/* Sidebar */}
            <Sidebar />
          </div>
        </div>
      </div>

      {/* Footer - full width */}
      <Footer />

      {/* Popups */}
      <Popup />

      {/* Overlay */}
      <Overlay />
    </div>
  );
};

Layout.displayName = 'Layout';
